>library(tidyverse)
>library(statnet)
>TotalDegree <-degree(AHS_Network)
>InDegree <-degree(AHS_Network,cmode = "indegree")
> OutDegree <-degree(AHS_Network, cmode = "outdegree")
> plot(InDegree,OutDegree)
> plot(InDegree,OutDegree,type = "n",xlab = "Received Friendship", ylab = "Sent Friendship")
> abline(0,1,lty=3)
> text(jitter(InDegree), jitter(OutDegree),network.vertex.names(AHS_Network),cex = 0.75,col = 2)
> set.vertex.attribute(AHS_Network, "TotalDegree", TotalDegree)
> set.vertex.attribute(AHS_Network,"InDegree", InDegree)
> set.vertex.attribute(AHS_Network, "OutDegree", OutDegree)
> set.seed(12345)
> gplot(AHS_Network, vertex.cex = (InDegree),vertex.sides = 50, displaylabels = FALSE)
> gplot(AHS_Network, vertex.cex = (InDegree)*.2,vertex.sides = 50, displaylabels = FALSE)
> closeness <-closeness(AHS_Network,gmode = "digraph",cmode = "directed")
> closeness
> hist(closeness,xlab = "closeness", prob=TRUE)
